name: CustomAreas
main: CustomAreas\Main
version: 1.12
api: [1.12.0]

load: POSTWORLD
author: luca28pet,ecoron
description: Protect areas in your server
website: https://github.com/ecoron/PrivateAreas
commands:
 customareas:
  description: Manage areas
  usage: "/area pos1 | pos2 | create | delete | whitelist | info | tp | remove"
  aliases: [area, ca, areas]
  permission: customareas.command
permissions:
 customareas.command:
  description: "Allows the user to manage areas"
  default: true
 customareas.remove:
  description: "Allows removal of areas created by other players"
  default: op
 customareas.tp:
  description: "Allows teleporting to an area"
  default: op
 customareas.info:
  description: "Display message if player move into an private area"
  default: op
 customareas.bypass:
  description: "Allows to have admin features"
  default: op